focal:
  exclude-all: true
  include: config/include.txt

closest:
  subsample-max-sequences: 10
  min-length: 10000
  min-date: "2022-01-01"
  priorities:
    type: "proximity"
    focus: "focal"

group:
  subsample-max-sequences: 10
  query: "(country == 'Canada')"
  priorities:
    type: "proximity"
    focus: "focal"

